ALTER TABLE BGM_AGIT_MATCHS
    ADD COLUMN BGM_AGIT_TOURNAMENT_SETTING_ID BIGINT NULL COMMENT 'BGM 아지트 대회 설정 ID';

ALTER TABLE BGM_AGIT_MATCHS
    ADD CONSTRAINT FK_BGM_AGIT_MATCHS_TOURNAMENT_SETTING
        FOREIGN KEY (BGM_AGIT_TOURNAMENT_SETTING_ID)
        REFERENCES BGM_AGIT_TOURNAMENT_SETTING (BGM_AGIT_TOURNAMENT_SETTING_ID)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;
