
-- =========================
-- DROP ALL TABLES
-- =========================
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS BGM_AGIT_RECORD;
DROP TABLE IF EXISTS BGM_AGIT_RECORD_HISTORY;

DROP TABLE IF EXISTS BGM_AGIT_MATCHS_HISTORY;
DROP TABLE IF EXISTS BGM_AGIT_MATCHS;

DROP TABLE IF EXISTS BGM_AGIT_YAKUMAN;
DROP TABLE IF EXISTS BGM_AGIT_YAKUMAN_TYPE;

DROP TABLE IF EXISTS BGM_AGIT_KML_MENU_ROLE;
DROP TABLE IF EXISTS BGM_AGIT_KML_MENU;
DROP TABLE IF EXISTS BGM_AGIT_KML_NOTICE;


DROP TABLE IF EXISTS BGM_AGIT_RULE;
DROP TABLE IF EXISTS BGM_AGIT_SETTING;
DROP TABLE IF EXISTS BGM_AGIT_LECTURE;


SET FOREIGN_KEY_CHECKS = 1;

-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- BGM_AGIT_SETTING Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_SETTING
CREATE TABLE BGM_AGIT_SETTING
(
    `BGM_AGIT_SETTING_ID`          BIGINT        NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 설정 ID',
    `BGM_AGIT_SETTING_TURNING`     INT           NULL        COMMENT 'BGM 아지트 설정 반환',
    `BGM_AGIT_SETTING_FIRST_UMA`   INT           NULL        COMMENT 'BGM 아지트 설정 1등 우마',
    `BGM_AGIT_SETTING_SECOND_UMA`  INT           NULL        COMMENT 'BGM 아지트 설정 2등 우마',
    `BGM_AGIT_SETTING_THIRD_UMA`   INT           NULL        COMMENT 'BGM 아지트 설정 3등 우마',
    `BGM_AGIT_SETTING_FOUR_UMA`    INT           NULL        COMMENT 'BGM 아지트 설정 4등 우마',
    `BGM_AGIT_SETTING_USE_STATUS`  VARCHAR(1)    NULL        COMMENT 'BGM 아지트 설정 사용 여부',
    `REGIST_DATE`                  DATETIME      NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                  DATETIME      NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_SETTING_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_SETTING
ALTER TABLE BGM_AGIT_SETTING COMMENT 'BGM_아지트_설정';




-- BGM_AGIT_KML_MENU Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_KML_MENU
CREATE TABLE BGM_AGIT_KML_MENU
(
    `BGM_AGIT_KML_MENU_ID`      BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 KML 메뉴 ID',
    `BGM_AGIT_KML_SUB_MENU_ID`  BIGINT           NULL        COMMENT 'BGM 아지트 KML 서브 메뉴 ID',
    `BGM_AGIT_KML_MENU_NAME`    VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 KML 메뉴 이름',
    `BGM_AGIT_KML_MENU_LINK`    VARCHAR(500)     NULL        COMMENT 'BGM 아지트 KML 메뉴 링크',
    `BGM_AGIT_KML_MENU_ORDERS`  INT              NULL        COMMENT 'BGM 아지트 KML 메뉴 순서',
    `BGM_AGIT_KML_ICON`         VARCHAR(500)     NULL        COMMENT 'BGM 아지트 KML 아이콘',
    `REGIST_DATE`               DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`               DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_KML_MENU_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_KML_MENU
ALTER TABLE BGM_AGIT_KML_MENU COMMENT 'BGM_아지트_KML_메뉴';

-- Foreign Key 설정 SQL - BGM_AGIT_KML_MENU(BGM_AGIT_KML_SUB_MENU_ID) -> BGM_AGIT_KML_MENU(BGM_AGIT_KML_MENU_ID)
ALTER TABLE BGM_AGIT_KML_MENU
    ADD CONSTRAINT FK_BGM_AGIT_KML_MENU_BGM_AGIT_KML_SUB_MENU_ID_BGM_AGIT_KML_MENU_ FOREIGN KEY (BGM_AGIT_KML_SUB_MENU_ID)
        REFERENCES BGM_AGIT_KML_MENU (BGM_AGIT_KML_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_KML_MENU(BGM_AGIT_KML_SUB_MENU_ID)
-- ALTER TABLE BGM_AGIT_KML_MENU
-- DROP FOREIGN KEY FK_BGM_AGIT_KML_MENU_BGM_AGIT_KML_SUB_MENU_ID_BGM_AGIT_KML_MENU_;


-- BGM_AGIT_MATCHS Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MATCHS
CREATE TABLE BGM_AGIT_MATCHS
(
    `BGM_AGIT_MATCHS_ID`                 BIGINT         NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 대국 ID',
    `BGM_AGIT_SETTING_ID`                BIGINT         NULL        COMMENT 'BGM 아지트 설정 ID',
    `BGM_AGIT_MATCHS_WIND`               VARCHAR(10)    NULL        COMMENT 'BGM 아지트 대국 바람',
    `BGM_AGIT_MATCHS_TOURNAMENT_STATUS`  VARCHAR(1)     NULL        COMMENT 'BGM 아지트 대국 대회 여부',
    `BGM_AGIT_MATCHS_DEL_STATUS`         VARCHAR(1)     NULL        COMMENT 'BGM 아지트 대국 삭제 여부',
    `REGIST_DATE`                        DATETIME       NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                        DATETIME       NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_MATCHS_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MATCHS
ALTER TABLE BGM_AGIT_MATCHS COMMENT 'BGM_아지트_대국';

-- Foreign Key 설정 SQL - BGM_AGIT_MATCHS(BGM_AGIT_SETTING_ID) -> BGM_AGIT_SETTING(BGM_AGIT_SETTING_ID)
ALTER TABLE BGM_AGIT_MATCHS
    ADD CONSTRAINT FK_BGM_AGIT_MATCHS_BGM_AGIT_SETTING_ID_BGM_AGIT_SETTING_BGM_AGIT FOREIGN KEY (BGM_AGIT_SETTING_ID)
        REFERENCES BGM_AGIT_SETTING (BGM_AGIT_SETTING_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MATCHS(BGM_AGIT_SETTING_ID)
-- ALTER TABLE BGM_AGIT_MATCHS
-- DROP FOREIGN KEY FK_BGM_AGIT_MATCHS_BGM_AGIT_SETTING_ID_BGM_AGIT_SETTING_BGM_AGIT;




-- BGM_AGIT_RECORD_HISTORY Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_RECORD_HISTORY
CREATE TABLE BGM_AGIT_RECORD_HISTORY
(
    `BGM_AGIT_RECORD_HISTORY_ID`  BIGINT          NULL        AUTO_INCREMENT COMMENT 'BGM 아지트 기록 이력 ID',
    `BGM_AGIT_RECORD_ID`          BIGINT          NULL        COMMENT 'BGM 아지트 기록 ID',
    `BGM_AGIT_MATCHS_ID`          BIGINT          NULL        COMMENT 'BGM 아지트 대국 ID',
    `BGM_AGIT_MEMBER_ID`          BIGINT          NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_RECORD_RANK`        INT             NULL        COMMENT 'BGM 아지트 기록 순위',
    `BGM_AGIT_RECORD_SCORE`       INT             NULL        COMMENT 'BGM 아지트 기록 점수',
    `BGM_AGIT_RECORD_POINT`       DOUBLE          NULL        COMMENT 'BGM 아지트 기록 승점',
    `BGM_AGIT_RECORD_SEAT`        VARCHAR(100)    NULL        COMMENT 'BGM 아지트 기록 자리',
    `REGIST_DATE`                 DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                 DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_RECORD_HISTORY_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_RECORD_HISTORY
ALTER TABLE BGM_AGIT_RECORD_HISTORY COMMENT 'BGM_아지트_기록_히스토리';


-- BGM_AGIT_MATCHS_HISTORY Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MATCHS_HISTORY
CREATE TABLE BGM_AGIT_MATCHS_HISTORY
(
    `BGM_AGIT_MATCHS_HISTORY_ID`             BIGINT           NULL        AUTO_INCREMENT COMMENT 'BGM 아지트 대국 이력 ID',
    `BGM_AGIT_MATCHS_ID`                     BIGINT           NULL        COMMENT 'BGM 아지트 대국 ID',
    `BGM_AGIT_SETTING_ID`                    BIGINT           NULL        COMMENT 'BGM 아지트 설정 ID',
    `BGM_AGIT_MEMBER_ID`                     BIGINT           NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_MATCHS_WIND`                   VARCHAR(10)      NULL        COMMENT 'BGM 아지트 대국 바람',
    `BGM_AGIT_MATCHS_TOURNAMENT_STATUS`      VARCHAR(1)       NULL        COMMENT 'BGM 아지트 대국 대회 여부',
    `BGM_AGIT_MATCHS_DEL_STATUS`             VARCHAR(1)       NULL        COMMENT 'BGM 아지트 대국 삭제 여부',
    `BGM_AGIT_MATCHS_HISTORY_CHANGE_REASON`  VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 대국 이력 변경 사유',
    `REGIST_DATE`                            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_MATCHS_HISTORY_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MATCHS_HISTORY
ALTER TABLE BGM_AGIT_MATCHS_HISTORY COMMENT 'BGM_아지트_대국_히스토리';


-- BGM_AGIT_KML_MENU_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_KML_MENU_ROLE
CREATE TABLE BGM_AGIT_KML_MENU_ROLE
(
    `BGM_AGIT_KML_MENU_ROLE_ID`  BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 KML 메뉴 권한 ID',
    `BGM_AGIT_ROLE_ID`           BIGINT      NULL        COMMENT 'BGM 아지트 권한 ID',
    `BGM_AGIT_KML_MENU_ID`       BIGINT      NULL        COMMENT 'BGM 아지트 KML 메뉴 ID',
    `REGIST_DATE`                DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_KML_MENU_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_KML_MENU_ROLE
ALTER TABLE BGM_AGIT_KML_MENU_ROLE COMMENT 'BGM_아지트_KML_메뉴_권한';

-- Foreign Key 설정 SQL - BGM_AGIT_KML_MENU_ROLE(BGM_AGIT_ROLE_ID) -> BGM_AGIT_ROLE(BGM_AGIT_ROLE_ID)
ALTER TABLE BGM_AGIT_KML_MENU_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_KML_MENU_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGI FOREIGN KEY (BGM_AGIT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE (BGM_AGIT_ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_KML_MENU_ROLE(BGM_AGIT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_KML_MENU_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_KML_MENU_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGI;

-- Foreign Key 설정 SQL - BGM_AGIT_KML_MENU_ROLE(BGM_AGIT_KML_MENU_ID) -> BGM_AGIT_KML_MENU(BGM_AGIT_KML_MENU_ID)
ALTER TABLE BGM_AGIT_KML_MENU_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_KML_MENU_ROLE_BGM_AGIT_KML_MENU_ID_BGM_AGIT_KML_MENU FOREIGN KEY (BGM_AGIT_KML_MENU_ID)
        REFERENCES BGM_AGIT_KML_MENU (BGM_AGIT_KML_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_KML_MENU_ROLE(BGM_AGIT_KML_MENU_ID)
-- ALTER TABLE BGM_AGIT_KML_MENU_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_KML_MENU_ROLE_BGM_AGIT_KML_MENU_ID_BGM_AGIT_KML_MENU;


-- BGM_AGIT_YAKUMAN Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_YAKUMAN
CREATE TABLE BGM_AGIT_YAKUMAN
(
    `BGM_AGIT_YAKUMAN_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 역만 ID',
    `BGM_AGIT_MEMBER_ID`     BIGINT          NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_MATCHS_ID`     BIGINT          NULL        COMMENT 'BGM 아지트 대국 ID',
    `BGM_AGIT_YAKUMAN_NAME`  VARCHAR(500)    NULL        COMMENT 'BGM 아지트 역만 이름',
    `BGM_AGIT_YAKUMAN_CONT`  VARCHAR(500)    NULL        COMMENT 'BGM 아지트 역만 내용',
    `REGIST_DATE`            DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_YAKUMAN_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_YAKUMAN
ALTER TABLE BGM_AGIT_YAKUMAN COMMENT 'BGM_아지트_역만';

-- Foreign Key 설정 SQL - BGM_AGIT_YAKUMAN(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_YAKUMAN
    ADD CONSTRAINT FK_BGM_AGIT_YAKUMAN_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_AGIT_ FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_YAKUMAN(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_YAKUMAN
-- DROP FOREIGN KEY FK_BGM_AGIT_YAKUMAN_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_AGIT_;

-- Foreign Key 설정 SQL - BGM_AGIT_YAKUMAN(BGM_AGIT_MATCHS_ID) -> BGM_AGIT_MATCHS(BGM_AGIT_MATCHS_ID)
ALTER TABLE BGM_AGIT_YAKUMAN
    ADD CONSTRAINT FK_BGM_AGIT_YAKUMAN_BGM_AGIT_MATCHS_ID_BGM_AGIT_MATCHS_BGM_AGIT_ FOREIGN KEY (BGM_AGIT_MATCHS_ID)
        REFERENCES BGM_AGIT_MATCHS (BGM_AGIT_MATCHS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_YAKUMAN(BGM_AGIT_MATCHS_ID)
-- ALTER TABLE BGM_AGIT_YAKUMAN
-- DROP FOREIGN KEY FK_BGM_AGIT_YAKUMAN_BGM_AGIT_MATCHS_ID_BGM_AGIT_MATCHS_BGM_AGIT_;


-- BGM_AGIT_YAKUMAN_TYPE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_YAKUMAN_TYPE
CREATE TABLE BGM_AGIT_YAKUMAN_TYPE
(
    `BGM_AGIT_YAKUMAN_TYPE_ID`      BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 역만 타입 ID',
    `BGM_AGIT_YAKUMAN_TYPE_NAME`    VARCHAR(500)    NULL        COMMENT 'BGM 아지트 역만 타입 이름',
    `BGM_AGIT_YAKUMAN_TYPE_ORDERS`  INT             NULL        COMMENT 'BGM 아지트 역만 타입 순서',
    `REGIST_DATE`                   DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                   DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_YAKUMAN_TYPE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_YAKUMAN_TYPE
ALTER TABLE BGM_AGIT_YAKUMAN_TYPE COMMENT 'BGM_아지트_역만_타입';


-- BGM_AGIT_RULE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_RULE
CREATE TABLE BGM_AGIT_RULE
(
    `BGM_AGIT_RULE_ID`            BIGINT        NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 룰 ID',
    `BGM_AGIT_TOURNAMENT_STATUS`  VARCHAR(1)    NULL        COMMENT 'BGM 아지트 대회 여부',
    `REGIST_DATE`                 DATETIME      NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                 DATETIME      NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_RULE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_RULE
ALTER TABLE BGM_AGIT_RULE COMMENT 'BGM_아지트_룰';



-- BGM_AGIT_KML_NOTICE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_KML_NOTICE
CREATE TABLE BGM_AGIT_KML_NOTICE
(
    `BGM_AGIT_KML_NOTICE_ID`     BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 KML 공지사항 ID',
    `BGM_AGIT_KML_NOTICE_TITLE`  VARCHAR(500)     NULL        COMMENT 'BGM 아지트 KML 공지사항 제목',
    `BGM_AGIT_KML_NOTICE_CONT`   VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 KML 공지사항 내용',
    `REGIST_DATE`                DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_KML_NOTICE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_KML_NOTICE
ALTER TABLE BGM_AGIT_KML_NOTICE COMMENT 'BGM_아지트_KML_공지사항';



-- BGM_AGIT_RECORD Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_RECORD
CREATE TABLE BGM_AGIT_RECORD
(
    `BGM_AGIT_RECORD_ID`     BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 기록 ID',
    `BGM_AGIT_MATCHS_ID`     BIGINT          NULL        COMMENT 'BGM 아지트 대국 ID',
    `BGM_AGIT_MEMBER_ID`     BIGINT          NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_RECORD_RANK`   INT             NULL        COMMENT 'BGM 아지트 기록 순위',
    `BGM_AGIT_RECORD_SCORE`  INT             NULL        COMMENT 'BGM 아지트 기록 점수',
    `BGM_AGIT_RECORD_POINT`  DOUBLE          NULL        COMMENT 'BGM 아지트 기록 승점',
    `BGM_AGIT_RECORD_SEAT`   VARCHAR(100)    NULL        COMMENT 'BGM 아지트 기록 자리',
    `REGIST_DATE`            DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_RECORD_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_RECORD
ALTER TABLE BGM_AGIT_RECORD COMMENT 'BGM_아지트_기록';

-- Foreign Key 설정 SQL - BGM_AGIT_RECORD(BGM_AGIT_MATCHS_ID) -> BGM_AGIT_MATCHS(BGM_AGIT_MATCHS_ID)
ALTER TABLE BGM_AGIT_RECORD
    ADD CONSTRAINT FK_BGM_AGIT_RECORD_BGM_AGIT_MATCHS_ID_BGM_AGIT_MATCHS_BGM_AGIT_M FOREIGN KEY (BGM_AGIT_MATCHS_ID)
        REFERENCES BGM_AGIT_MATCHS (BGM_AGIT_MATCHS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_RECORD(BGM_AGIT_MATCHS_ID)
-- ALTER TABLE BGM_AGIT_RECORD
-- DROP FOREIGN KEY FK_BGM_AGIT_RECORD_BGM_AGIT_MATCHS_ID_BGM_AGIT_MATCHS_BGM_AGIT_M;

-- Foreign Key 설정 SQL - BGM_AGIT_RECORD(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_RECORD
    ADD CONSTRAINT FK_BGM_AGIT_RECORD_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_AGIT_M FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_RECORD(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_RECORD
-- DROP FOREIGN KEY FK_BGM_AGIT_RECORD_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_AGIT_M;
-- 테이블 생성 SQL - BGM_AGIT_LECTURE_SLOT
CREATE TABLE BGM_AGIT_LECTURE_SLOT
(
    `BGM_AGIT_LECTURE_SLOT_ID`               BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 강의 슬롯 ID',
    `BGM_AGIT_LECTURE_SLOT_START_DATE`       DATE        NULL        COMMENT 'BGM 아지트 강의 슬롯 시작 일시',
    `BGM_AGIT_LECTURE_SLOT_START_TIME`       TIME        NULL        COMMENT 'BGM 아지트 강의 슬롯 시작 시간',
    `BGM_AGIT_LECTURE_SLOT_END_TIME`         TIME        NULL        COMMENT 'BGM 아지트 강의 슬롯 종료 시간',
    `BGM_AGIT_LECTURE_SLOT_CAPACITY`         INT         NULL        DEFAULT 4 COMMENT 'BGM 아지트 강의 슬롯 정원',
    `BGM_AGIT_LECTURE_SLOT_APPROVAL_PEOPLE`  INT         NULL        DEFAULT 0 COMMENT 'BGM 아지트 강의 슬롯 승인 인원',
    `REGIST_DATE`                            DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                            DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_LECTURE_SLOT_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_LECTURE_SLOT
ALTER TABLE BGM_AGIT_LECTURE_SLOT COMMENT 'BGM_아지트_강의_슬롯';

-- 테이블 생성 SQL - BGM_AGIT_LECTURE
CREATE TABLE BGM_AGIT_LECTURE
(
    `BGM_AGIT_LECTURE_ID`               BIGINT        NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 강의 ID',
    `BGM_AGIT_MEMBER_ID`                BIGINT        NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_LECTURE_SLOT_ID`          BIGINT        NULL        COMMENT 'BGM 아지트 강의 슬롯 ID',
    `BGM_AGIT_LECTURE_APPROVAL_STATUS`  VARCHAR(1)    NULL        DEFAULT 'N' COMMENT 'BGM 아지트 강의 승인 여부. ''N''',
    `BGM_AGIT_LECTURE_CANCEL_STATUS`    VARCHAR(1)    NULL        DEFAULT 'N' COMMENT 'BGM 아지트 강의 취소 여부. ''N''',
    `REGIST_DATE`                       DATETIME      NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                       DATETIME      NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
     PRIMARY KEY (BGM_AGIT_LECTURE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_LECTURE
ALTER TABLE BGM_AGIT_LECTURE COMMENT 'BGM_아지트_강의';

-- Foreign Key 설정 SQL - BGM_AGIT_LECTURE(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_LECTURE
    ADD CONSTRAINT FK_BGM_AGIT_LECTURE_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_AGIT_ FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_LECTURE(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_LECTURE
-- DROP FOREIGN KEY FK_BGM_AGIT_LECTURE_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_AGIT_;

-- Foreign Key 설정 SQL - BGM_AGIT_LECTURE(BGM_AGIT_LECTURE_SLOT_ID) -> BGM_AGIT_LECTURE_SLOT(BGM_AGIT_LECTURE_SLOT_ID)
ALTER TABLE BGM_AGIT_LECTURE
    ADD CONSTRAINT FK_BGM_AGIT_LECTURE_BGM_AGIT_LECTURE_SLOT_ID_BGM_AGIT_LECTURE_SL FOREIGN KEY (BGM_AGIT_LECTURE_SLOT_ID)
        REFERENCES BGM_AGIT_LECTURE_SLOT (BGM_AGIT_LECTURE_SLOT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_LECTURE(BGM_AGIT_LECTURE_SLOT_ID)
-- ALTER TABLE BGM_AGIT_LECTURE
-- DROP FOREIGN KEY FK_BGM_AGIT_LECTURE_BGM_AGIT_LECTURE_SLOT_ID_BGM_AGIT_LECTURE_SL;