-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- BGM_AGIT_MAIN_MENU Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MAIN_MENU
CREATE TABLE BGM_AGIT_MAIN_MENU
(
    `BGM_AGIT_MAIN_MENU_ID`  BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 메인 메뉴 ID',
    `BGM_AGIT_SUB_MENU_ID`   BIGINT           NULL        COMMENT 'BGM 아지트 서브 메뉴 ID',
    `BGM_AGIT_AREA_ID`       BIGINT           NULL        COMMENT 'BGM 아지트 영역 ID',
    `BGM_AGIT_MENU_NAME`     VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 메뉴 이름',
    `BGM_AGIT_MENU_LINK`     VARCHAR(500)     NULL        COMMENT 'BGM 아지트 메뉴 링크',
    `REGIST_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MAIN_MENU_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MAIN_MENU
ALTER TABLE BGM_AGIT_MAIN_MENU COMMENT 'BGM_아지트_메인_메뉴';

-- Foreign Key 설정 SQL - BGM_AGIT_MAIN_MENU(BGM_AGIT_SUB_MENU_ID) -> BGM_AGIT_MAIN_MENU(BGM_AGIT_MAIN_MENU_ID)
ALTER TABLE BGM_AGIT_MAIN_MENU
    ADD CONSTRAINT FK_BGM_AGIT_MAIN_MENU_BGM_AGIT_SUB_MENU_ID_BGM_AGIT_MAIN_MENU_BG FOREIGN KEY (BGM_AGIT_SUB_MENU_ID)
        REFERENCES BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MAIN_MENU(BGM_AGIT_SUB_MENU_ID)
-- ALTER TABLE BGM_AGIT_MAIN_MENU
-- DROP FOREIGN KEY FK_BGM_AGIT_MAIN_MENU_BGM_AGIT_SUB_MENU_ID_BGM_AGIT_MAIN_MENU_BG;


-- BGM_AGIT_NOTICE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_NOTICE
CREATE TABLE BGM_AGIT_NOTICE
(
    `BGM_AGIT_NOTICE_ID`     BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 공지사항 ID',
    `BGM_AGIT_NOTICE_TITLE`  VARCHAR(500)     NULL        COMMENT 'BGM 아지트 공지사항 제목',
    `BGM_AGIT_NOTICE_CONT`   VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 공지사항 내용',
    `BGM_AGIT_NOTICE_TYPE`   VARCHAR(100)     NULL        COMMENT 'BGM 아지트 공지사항 타입',
    `REGIST_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_NOTICE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_NOTICE
ALTER TABLE BGM_AGIT_NOTICE COMMENT 'BGM_아지트_공지사항';


-- BGM_AGIT_IMAGE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_IMAGE
CREATE TABLE BGM_AGIT_IMAGE
(
    `BGM_AGIT_IMAGE_ID`        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 이미지 ID',
    `BGM_AGIT_MAIN_MENU_ID`    BIGINT          NULL        COMMENT 'BGM 아지트 메인 메뉴 ID',
    `BGM_AGIT_IMAGE_LABEL`     VARCHAR(500)    NULL        COMMENT 'BGM 아지트 이미지 라벨',
    `BGM_AGIT_MENU_LINK`       VARCHAR(500)    NULL        COMMENT 'BGM 아지트 메뉴 링크',
    `BGM_AGIT_IMAGE_GROUPS`    VARCHAR(100)    NULL        COMMENT 'BGM 아지트 이미지 그룹',
    `BGM_AGIT_IMAGE_CATEGORY`  VARCHAR(500)    NULL        COMMENT 'BGM 아지트 이미지 카테고리',
    `BGM_AGIT_IMAGE_URL`       VARCHAR(500)    NULL        COMMENT 'BGM 아지트 이미지 URL',
    `REGIST_DATE`              DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`              DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_IMAGE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_IMAGE
ALTER TABLE BGM_AGIT_IMAGE COMMENT 'BGM_아지트_이미지';

-- Foreign Key 설정 SQL - BGM_AGIT_IMAGE(BGM_AGIT_MAIN_MENU_ID) -> BGM_AGIT_MAIN_MENU(BGM_AGIT_MAIN_MENU_ID)
ALTER TABLE BGM_AGIT_IMAGE
    ADD CONSTRAINT FK_BGM_AGIT_IMAGE_BGM_AGIT_MAIN_MENU_ID_BGM_AGIT_MAIN_MENU_BGM_A FOREIGN KEY (BGM_AGIT_MAIN_MENU_ID)
        REFERENCES BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_IMAGE(BGM_AGIT_MAIN_MENU_ID)
-- ALTER TABLE BGM_AGIT_IMAGE
-- DROP FOREIGN KEY FK_BGM_AGIT_IMAGE_BGM_AGIT_MAIN_MENU_ID_BGM_AGIT_MAIN_MENU_BGM_A;


-- BGM_AGIT_MEMBER Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MEMBER
CREATE TABLE BGM_AGIT_MEMBER
(
    `BGM_AGIT_MEMBER_ID`         BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_MEMBER_EMAIL`      VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 이메일',
    `BGM_AGIT_MEMBER_NAME`       VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 이름',
    `BGM_AGIT_MEMBER_PASSWORD`   VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 비밀번호',
    `BGM_AGIT_SOCIAL_TYPE`       VARCHAR(100)    NULL        COMMENT 'BGM 아지트 소셜 타입',
    `BGM_AGIT_MEMBER_SOCIAL_ID`  VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 소셜 ID',
    `BGM_AGIT_MEMBER_PHONE_NO`   VARCHAR(500)    NULL        COMMENT 'BGM 아지트 회원 폰 번호',
    `REGIST_DATE`                DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MEMBER_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MEMBER
ALTER TABLE BGM_AGIT_MEMBER COMMENT 'BGM_아지트_회원';


-- BGM_AGIT_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_ROLE
CREATE TABLE BGM_AGIT_ROLE
(
    `BGM_AGIT_ROLE_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 권한 ID',
    `BGM_AGIT_ROLE_NAME`  VARCHAR(100)    NULL        COMMENT 'BGM 아지트 권한 이름',
    `REGIST_DATE`         DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`         DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_ROLE
ALTER TABLE BGM_AGIT_ROLE COMMENT 'BGM_아지트_권한';


-- BGM_AGIT_URL_RESOURCES Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_URL_RESOURCES
CREATE TABLE BGM_AGIT_URL_RESOURCES
(
    `BGM_AGIT_URL_RESOURCES_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 URL 리소스 ID',
    `BGM_AGIT_URL_RESOURCES_PATH`  VARCHAR(500)    NULL        COMMENT 'BGM 아지트 URL 리소스 경로',
    `BGM_AGIT_URL_HTTP_METHOD`     VARCHAR(100)    NULL        COMMENT 'BGM 아지트 URL HTTP 메서드',
    `REGIST_DATE`                  DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                  DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_URL_RESOURCES_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_URL_RESOURCES
ALTER TABLE BGM_AGIT_URL_RESOURCES COMMENT 'BGM_아지트_URL_리소스';


-- BGM_AGIT_MEMBER_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MEMBER_ROLE
CREATE TABLE BGM_AGIT_MEMBER_ROLE
(
    `BGM_AGIT_MEMBER_ROLE_ID`  BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 회원 권한 ID',
    `BGM_AGIT_MEMBER_ID`       BIGINT      NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_ROLE_ID`         BIGINT      NULL        COMMENT 'BGM 아지트 권한 ID',
    `REGIST_DATE`              DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`              DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MEMBER_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MEMBER_ROLE
ALTER TABLE BGM_AGIT_MEMBER_ROLE COMMENT 'BGM_아지트_회원_권한';

-- Foreign Key 설정 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_MEMBER_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_A FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_MEMBER_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_A;

-- Foreign Key 설정 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_ROLE_ID) -> BGM_AGIT_ROLE(BGM_AGIT_ROLE_ID)
ALTER TABLE BGM_AGIT_MEMBER_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGIT_ FOREIGN KEY (BGM_AGIT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE (BGM_AGIT_ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_MEMBER_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGIT_;


-- BGM_AGIT_ROLE_HIERARCHY Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_ROLE_HIERARCHY
CREATE TABLE BGM_AGIT_ROLE_HIERARCHY
(
    `BGM_AGIT_ROLE_HIERARCHY_ID`  BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 권한 계층 ID',
    `BGM_AGIT_ROLE_NAME`          VARCHAR(100)    NULL        COMMENT 'BGM 아지트 권한 이름',
    `BGM_AGIT_PARENT_ROLE_ID`     BIGINT          NULL        COMMENT 'BGM 아지트 상위 권한 ID',
    `REGIST_DATE`                 DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                 DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_ROLE_HIERARCHY_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_ROLE_HIERARCHY
ALTER TABLE BGM_AGIT_ROLE_HIERARCHY COMMENT 'BGM_아지트_권한_계층';

-- Foreign Key 설정 SQL - BGM_AGIT_ROLE_HIERARCHY(BGM_AGIT_PARENT_ROLE_ID) -> BGM_AGIT_ROLE_HIERARCHY(BGM_AGIT_ROLE_HIERARCHY_ID)
ALTER TABLE BGM_AGIT_ROLE_HIERARCHY
    ADD CONSTRAINT FK_BGM_AGIT_ROLE_HIERARCHY_BGM_AGIT_PARENT_ROLE_ID_BGM_AGIT_ROLE FOREIGN KEY (BGM_AGIT_PARENT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE_HIERARCHY (BGM_AGIT_ROLE_HIERARCHY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_ROLE_HIERARCHY(BGM_AGIT_PARENT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_ROLE_HIERARCHY
-- DROP FOREIGN KEY FK_BGM_AGIT_ROLE_HIERARCHY_BGM_AGIT_PARENT_ROLE_ID_BGM_AGIT_ROLE;


-- BGM_AGIT_URL_RESOURCES_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_URL_RESOURCES_ROLE
CREATE TABLE BGM_AGIT_URL_RESOURCES_ROLE
(
    `BGM_AGIT_URL_RESOURCES_ROLE_ID`  BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 URL 리소스 권한 ID',
    `BGM_AGIT_ROLE_ID`                BIGINT      NULL        COMMENT 'BGM 아지트 권한 ID',
    `BGM_AGIT_URL_RESOURCES_ID`       BIGINT      NULL        COMMENT 'BGM 아지트 URL 리소스 ID',
    `REGIST_DATE`                     DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                     DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_URL_RESOURCES_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_URL_RESOURCES_ROLE
ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE COMMENT 'BGM_아지트_URL_리소스_권한';

-- Foreign Key 설정 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_URL_RESOURCES_ID) -> BGM_AGIT_URL_RESOURCES(BGM_AGIT_URL_RESOURCES_ID)
ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_URL_RESOURCES_ID_BGM_AGI FOREIGN KEY (BGM_AGIT_URL_RESOURCES_ID)
        REFERENCES BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_URL_RESOURCES_ID)
-- ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_URL_RESOURCES_ID_BGM_AGI;

-- Foreign Key 설정 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_ROLE_ID) -> BGM_AGIT_ROLE(BGM_AGIT_ROLE_ID)
ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BG FOREIGN KEY (BGM_AGIT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE (BGM_AGIT_ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BG;


-- BGM_AGIT_RESERVATION Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_RESERVATION
CREATE TABLE BGM_AGIT_RESERVATION
(
    `BGM_AGIT_RESERVATION_ID`               BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 예약 ID',
    `BGM_AGIT_MEMBER_ID`                    BIGINT          NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_IMAGE_ID`                     BIGINT          NULL        COMMENT 'BGM 아지트 이미지 ID',
    `BGM_AGIT_RESERVATION_TYPE`             VARCHAR(100)    NULL        COMMENT 'BGM 아지트 예약 타입',
    `BGM_AGIT_RESERVATION_START_DATE`       DATE            NULL        COMMENT 'BGM 아지트 예약 시작 일시',
    `BGM_AGIT_RESERVATION_START_TIME`       TIME            NULL        COMMENT 'BGM 아지트 예약 시작 시간',
    `BGM_AGIT_RESERVATION_END_TIME`         TIME            NULL        COMMENT 'BGM 아지트 예약 종료 시간',
    `BGM_AGIT_RESERVATION_APPROVAL_STATUS`  VARCHAR(1)      NULL        DEFAULT 'N' COMMENT 'BGM 아지트 예약 승인 여부. ''N''',
    `BGM_AGIT_RESERVATION_CANCEL_STATUS`    VARCHAR(1)      NULL        DEFAULT 'N' COMMENT 'BGM 아지트 예약 취소 여부. ''N''',
    `BGM_AGIT_RESERVATION_NO`               BIGINT          NULL        COMMENT 'BGM 아지트 예약 번호',
    `REGIST_DATE`                           DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                           DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_RESERVATION_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_RESERVATION
ALTER TABLE BGM_AGIT_RESERVATION COMMENT 'BGM_아지트_예약';

-- Foreign Key 설정 SQL - BGM_AGIT_RESERVATION(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_RESERVATION
    ADD CONSTRAINT FK_BGM_AGIT_RESERVATION_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_A FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_RESERVATION(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_RESERVATION
-- DROP FOREIGN KEY FK_BGM_AGIT_RESERVATION_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_A;

-- Foreign Key 설정 SQL - BGM_AGIT_RESERVATION(BGM_AGIT_IMAGE_ID) -> BGM_AGIT_IMAGE(BGM_AGIT_IMAGE_ID)
ALTER TABLE BGM_AGIT_RESERVATION
    ADD CONSTRAINT FK_BGM_AGIT_RESERVATION_BGM_AGIT_IMAGE_ID_BGM_AGIT_IMAGE_BGM_AGI FOREIGN KEY (BGM_AGIT_IMAGE_ID)
        REFERENCES BGM_AGIT_IMAGE (BGM_AGIT_IMAGE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_RESERVATION(BGM_AGIT_IMAGE_ID)
-- ALTER TABLE BGM_AGIT_RESERVATION
-- DROP FOREIGN KEY FK_BGM_AGIT_RESERVATION_BGM_AGIT_IMAGE_ID_BGM_AGIT_IMAGE_BGM_AGI;


-- BGM_AGIT_NOTICE_FILE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_NOTICE_FILE
CREATE TABLE BGM_AGIT_NOTICE_FILE
(
    `BGM_AGIT_NOTICE_FILE_ID`         BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 공지사항 파일 ID',
    `BGM_AGIT_NOTICE_ID`              BIGINT           NULL        COMMENT 'BGM 아지트 공지사항 ID',
    `BGM_AGIT_NOTICE_FILE_NAME`       VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 공지사항 파일 이름',
    `BGM_AGIT_NOTICE_FILE_UUID_NAME`  VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 공지사항 파일 UUID 이름',
    `BGM_AGIT_NOTICE_FILE_URL`        VARCHAR(500)     NULL        COMMENT 'BGM 아지트 공지사항 파일 URL',
    `REGIST_DATE`                     DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                     DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_NOTICE_FILE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_NOTICE_FILE
ALTER TABLE BGM_AGIT_NOTICE_FILE COMMENT 'BGM_아지트_공지사항_파일';

-- Foreign Key 설정 SQL - BGM_AGIT_NOTICE_FILE(BGM_AGIT_NOTICE_ID) -> BGM_AGIT_NOTICE(BGM_AGIT_NOTICE_ID)
ALTER TABLE BGM_AGIT_NOTICE_FILE
    ADD CONSTRAINT FK_BGM_AGIT_NOTICE_FILE_BGM_AGIT_NOTICE_ID_BGM_AGIT_NOTICE_BGM_A FOREIGN KEY (BGM_AGIT_NOTICE_ID)
        REFERENCES BGM_AGIT_NOTICE (BGM_AGIT_NOTICE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_NOTICE_FILE(BGM_AGIT_NOTICE_ID)
-- ALTER TABLE BGM_AGIT_NOTICE_FILE
-- DROP FOREIGN KEY FK_BGM_AGIT_NOTICE_FILE_BGM_AGIT_NOTICE_ID_BGM_AGIT_NOTICE_BGM_A;


-- BGM_AGIT_MENU_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MENU_ROLE
CREATE TABLE BGM_AGIT_MENU_ROLE
(
    `BGM_AGIT_MENU_ROLE_ID`  BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 메뉴 권한 ID',
    `BGM_AGIT_ROLE_ID`       BIGINT      NULL        COMMENT 'BGM 아지트 권한 ID',
    `BGM_AGIT_MAIN_MENU_ID`  BIGINT      NULL        COMMENT 'BGM 아지트 메인 메뉴 ID',
    `REGIST_DATE`            DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MENU_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MENU_ROLE
ALTER TABLE BGM_AGIT_MENU_ROLE COMMENT 'BGM_아지트_메뉴_권한';

-- Foreign Key 설정 SQL - BGM_AGIT_MENU_ROLE(BGM_AGIT_MAIN_MENU_ID) -> BGM_AGIT_MAIN_MENU(BGM_AGIT_MAIN_MENU_ID)
ALTER TABLE BGM_AGIT_MENU_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_MENU_ROLE_BGM_AGIT_MAIN_MENU_ID_BGM_AGIT_MAIN_MENU_B FOREIGN KEY (BGM_AGIT_MAIN_MENU_ID)
        REFERENCES BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MENU_ROLE(BGM_AGIT_MAIN_MENU_ID)
-- ALTER TABLE BGM_AGIT_MENU_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_MENU_ROLE_BGM_AGIT_MAIN_MENU_ID_BGM_AGIT_MAIN_MENU_B;

-- Foreign Key 설정 SQL - BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID) -> BGM_AGIT_ROLE(BGM_AGIT_ROLE_ID)
ALTER TABLE BGM_AGIT_MENU_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_MENU_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGIT_RO FOREIGN KEY (BGM_AGIT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE (BGM_AGIT_ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_MENU_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_MENU_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGIT_RO;


-- BGM_AGIT_RSA Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_RSA
CREATE TABLE BGM_AGIT_RSA
(
    `BGM_AGIT_RSA_ID`           BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 RSA ID',
    `BGM_AGIT_RSA_PRIVATE_KEY`  VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 RSA 개인 키',
    `REGIST_DATE`               DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`               DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_RSA_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_RSA
ALTER TABLE BGM_AGIT_RSA COMMENT 'BGM_아지트_RSA';


-- BGM_AGIT_REFRESH_TOKEN Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_REFRESH_TOKEN
CREATE TABLE BGM_AGIT_REFRESH_TOKEN
(
    `BGM_AGIT_REFRESH_TOKEN_ID`      BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 리프레쉬 토큰 ID',
    `BGM_AGIT_MEMBER_ID`             BIGINT           NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_REFRESH_TOKEN_VALUE`   VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 리프레쉬 토큰 값',
    `BGM_AGIT_REFRESH_EXPIRES_DATE`  DATETIME         NULL        COMMENT 'BGM 아지트 리프레쉬 만료 일시',
    `BGM_AGIT_REFRESH_PLATFORM_ID`   VARCHAR(100)     NULL        COMMENT 'BGM 아지트 리프레쉬 플랫폼 ID',
    `REGIST_DATE`                    DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                    DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_REFRESH_TOKEN_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_REFRESH_TOKEN
ALTER TABLE BGM_AGIT_REFRESH_TOKEN COMMENT 'BGM_AGIT_리프레쉬_토큰';

-- Foreign Key 설정 SQL - BGM_AGIT_REFRESH_TOKEN(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_REFRESH_TOKEN
    ADD CONSTRAINT FK_BGM_AGIT_REFRESH_TOKEN_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_REFRESH_TOKEN(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_REFRESH_TOKEN
-- DROP FOREIGN KEY FK_BGM_AGIT_REFRESH_TOKEN_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM;


-- BGM_AGIT_BIZTALK_TOKEN Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_BIZTALK_TOKEN
CREATE TABLE BGM_AGIT_BIZTALK_TOKEN
(
    `BGM_AGIT_BIZTALK_TOKEN_ID`            BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 비즈톡 토큰 ID',
    `BGM_AGIT_BIZTALK_TOKEN_VALUE`         VARCHAR(500)    NULL        COMMENT 'BGM 아지트 비즈톡 토큰 값',
    `BGM_AGIT_BIZTALK_TOKEN_EXPIRES_DATE`  DATETIME        NULL        COMMENT 'BGM 아지트 비즈톡 토큰 만료 일시',
    `REGIST_DATE`                          DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                          DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_BIZTALK_TOKEN_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_BIZTALK_TOKEN
ALTER TABLE BGM_AGIT_BIZTALK_TOKEN COMMENT 'BGM_아지트_비즈톡_토큰';


-- BGM_AGIT_BIZTALK_SEND_HISTORY Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_BIZTALK_SEND_HISTORY
CREATE TABLE BGM_AGIT_BIZTALK_SEND_HISTORY
(
    `BGM_AGIT_BIZTALK_SEND_HISTORY_ID`           BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 비즈톡 전송 이력 ID',
    `BGM_AGIT_BIZTALK_HISTORY_SUBJECT_TYPE`      VARCHAR(100)     NULL        COMMENT 'BGM 아지트 비즈톡 이력 대상 타입',
    `BGM_AGIT_BIZTALK_SEND_HISTORY_SUBJECT_ID`   BIGINT           NULL        COMMENT 'BGM 아지트 비즈톡 전송 이력 대상 ID',
    `BGM_AGIT_BIZTALK_SEND_HISTORY_CONT`         VARCHAR(500)     NULL        COMMENT 'BGM 아지트 비즈톡 전송 이력 내용',
    `BGM_AGIT_BIZTALK_SEND_HISTORY_MSG_IDX`      VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 비즈톡 전송 이력 메세지 고유값',
    `BGM_AGIT_BIZTALK_SEND_HISTORY_RESULT_CODE`  VARCHAR(100)     NULL        COMMENT 'BGM 아지트 비즈톡 전송 이력 결과 코드',
    `REGIST_DATE`                                DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                                DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_BIZTALK_SEND_HISTORY_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_BIZTALK_SEND_HISTORY
ALTER TABLE BGM_AGIT_BIZTALK_SEND_HISTORY COMMENT 'BGM_아지트_비즈톡_전송_이력';