-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- BGM_AGIT_MEMBER Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MEMBER
CREATE TABLE BGM_AGIT_MEMBER
(
    `BGM_AGIT_MEMBER_ID`         BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_MEMBER_EMAIL`      VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 이메일',
    `BGM_AGIT_MEMBER_NAME`       VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 이름',
    `BGM_AGIT_MEMBER_PASSWORD`   VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 비밀번호',
    `BGM_AGIT_SOCIAL_TYPE`       VARCHAR(100)    NULL        COMMENT 'BGM 아지트 소셜 타입',
    `BGM_AGIT_MEMBER_SOCIAL_ID`  VARCHAR(100)    NULL        COMMENT 'BGM 아지트 회원 소셜 ID',
    `REGIST_DATE`                DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MEMBER_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MEMBER
ALTER TABLE BGM_AGIT_MEMBER COMMENT 'BGM_아지트_회원';


-- BGM_AGIT_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_ROLE
CREATE TABLE BGM_AGIT_ROLE
(
    `BGM_AGIT_ROLE_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 권한 ID',
    `BGM_AGIT_ROLE_NAME`  VARCHAR(100)    NULL        COMMENT 'BGM 아지트 권한 이름',
    `REGIST_DATE`         DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`         DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_ROLE
ALTER TABLE BGM_AGIT_ROLE COMMENT 'BGM_아지트_권한';


-- BGM_AGIT_URL_RESOURCES Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_URL_RESOURCES
CREATE TABLE BGM_AGIT_URL_RESOURCES
(
    `BGM_AGIT_URL_RESOURCES_ID`    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 URL 리소스 ID',
    `BGM_AGIT_URL_RESOURCES_PATH`  VARCHAR(500)    NULL        COMMENT 'BGM 아지트 URL 리소스 경로',
    `REGIST_DATE`                  DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                  DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_URL_RESOURCES_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_URL_RESOURCES
ALTER TABLE BGM_AGIT_URL_RESOURCES COMMENT 'BGM_아지트_URL_리소스';


-- 테이블 생성 SQL - BGM_AGIT_MAIN_MENU
CREATE TABLE BGM_AGIT_MAIN_MENU
(
    `BGM_AGIT_MAIN_MENU_ID`  BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 메인 메뉴 ID',
    `BGM_AGIT_SUB_MENU_ID`   BIGINT           NULL        COMMENT 'BGM 아지트 서브 메뉴 ID',
    `BGM_AGIT_AREA_ID`       BIGINT           NULL        COMMENT 'BGM 아지트 영역 ID',
    `BGM_AGIT_MENU_NAME`     VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 메뉴 이름',
    `BGM_AGIT_MENU_LINK`     VARCHAR(500)     NULL        COMMENT 'BGM 아지트 메뉴 링크',
    `REGIST_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MAIN_MENU_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MAIN_MENU
ALTER TABLE BGM_AGIT_MAIN_MENU COMMENT 'BGM_아지트_메인_메뉴';

-- Foreign Key 설정 SQL - BGM_AGIT_MAIN_MENU(BGM_AGIT_SUB_MENU_ID) -> BGM_AGIT_MAIN_MENU(BGM_AGIT_MAIN_MENU_ID)
ALTER TABLE BGM_AGIT_MAIN_MENU
    ADD CONSTRAINT FK_BGM_AGIT_MAIN_MENU_BGM_AGIT_SUB_MENU_ID_BGM_AGIT_MAIN_MENU_BG FOREIGN KEY (BGM_AGIT_SUB_MENU_ID)
        REFERENCES BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MAIN_MENU(BGM_AGIT_SUB_MENU_ID)
-- ALTER TABLE BGM_AGIT_MAIN_MENU
-- DROP FOREIGN KEY FK_BGM_AGIT_MAIN_MENU_BGM_AGIT_SUB_MENU_ID_BGM_AGIT_MAIN_MENU_BG;

-- BGM_AGIT_MEMBER_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MEMBER_ROLE
CREATE TABLE BGM_AGIT_MEMBER_ROLE
(
    `BGM_AGIT_MEMBER_ROLE_ID`  BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 회원 권한 ID',
    `BGM_AGIT_MEMBER_ID`       BIGINT      NULL        COMMENT 'BGM 아지트 회원 ID',
    `BGM_AGIT_ROLE_ID`         BIGINT      NULL        COMMENT 'BGM 아지트 권한 ID',
    `REGIST_DATE`              DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`              DATETIME    NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MEMBER_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MEMBER_ROLE
ALTER TABLE BGM_AGIT_MEMBER_ROLE COMMENT 'BGM_아지트_회원_권한';

-- Foreign Key 설정 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_MEMBER_ID) -> BGM_AGIT_MEMBER(BGM_AGIT_MEMBER_ID)
ALTER TABLE BGM_AGIT_MEMBER_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_A FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_MEMBER_ID)
-- ALTER TABLE BGM_AGIT_MEMBER_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_MEMBER_ID_BGM_AGIT_MEMBER_BGM_A;

-- Foreign Key 설정 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_ROLE_ID) -> BGM_AGIT_ROLE(BGM_AGIT_ROLE_ID)
ALTER TABLE BGM_AGIT_MEMBER_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGIT_ FOREIGN KEY (BGM_AGIT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE (BGM_AGIT_ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MEMBER_ROLE(BGM_AGIT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_MEMBER_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_MEMBER_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BGM_AGIT_;


-- BGM_AGIT_ROLE_HIERARCHY Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_ROLE_HIERARCHY
CREATE TABLE BGM_AGIT_ROLE_HIERARCHY
(
    `BGM_AGIT_ROLE_HIERARCHY_ID`  BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 권한 계층 ID',
    `BGM_AGIT_ROLE_NAME`          VARCHAR(100)    NULL        COMMENT 'BGM 아지트 권한 이름',
    `BGM_AGIT_PARENT_ROLE_ID`     BIGINT          NULL        COMMENT 'BGM 아지트 상위 권한 ID',
    `REGIST_DATE`                 DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                 DATETIME        NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_ROLE_HIERARCHY_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_ROLE_HIERARCHY
ALTER TABLE BGM_AGIT_ROLE_HIERARCHY COMMENT 'BGM_아지트_권한_계층';

-- Foreign Key 설정 SQL - BGM_AGIT_ROLE_HIERARCHY(BGM_AGIT_PARENT_ROLE_ID) -> BGM_AGIT_ROLE_HIERARCHY(BGM_AGIT_ROLE_HIERARCHY_ID)
ALTER TABLE BGM_AGIT_ROLE_HIERARCHY
    ADD CONSTRAINT FK_BGM_AGIT_ROLE_HIERARCHY_BGM_AGIT_PARENT_ROLE_ID_BGM_AGIT_ROLE FOREIGN KEY (BGM_AGIT_PARENT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE_HIERARCHY (BGM_AGIT_ROLE_HIERARCHY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_ROLE_HIERARCHY(BGM_AGIT_PARENT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_ROLE_HIERARCHY
-- DROP FOREIGN KEY FK_BGM_AGIT_ROLE_HIERARCHY_BGM_AGIT_PARENT_ROLE_ID_BGM_AGIT_ROLE;


-- BGM_AGIT_URL_RESOURCES_ROLE Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_URL_RESOURCES_ROLE
CREATE TABLE BGM_AGIT_URL_RESOURCES_ROLE
(
    `BGM_AGIT_URL_RESOURCES_ROLE_ID`  BIGINT      NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 URL 리소스 권한 ID',
    `BGM_AGIT_ROLE_ID`                BIGINT      NULL        COMMENT 'BGM 아지트 권한 ID',
    `BGM_AGIT_URL_RESOURCES_ID`       BIGINT      NULL        COMMENT 'BGM 아지트 URL 리소스 ID',
    `REGIST_DATE`                     DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                     DATETIME    NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_URL_RESOURCES_ROLE_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_URL_RESOURCES_ROLE
ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE COMMENT 'BGM_아지트_URL_리소스_권한';

-- Foreign Key 설정 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_URL_RESOURCES_ID) -> BGM_AGIT_URL_RESOURCES(BGM_AGIT_URL_RESOURCES_ID)
ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_URL_RESOURCES_ID_BGM_AGI FOREIGN KEY (BGM_AGIT_URL_RESOURCES_ID)
        REFERENCES BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_URL_RESOURCES_ID)
-- ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_URL_RESOURCES_ID_BGM_AGI;

-- Foreign Key 설정 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_ROLE_ID) -> BGM_AGIT_ROLE(BGM_AGIT_ROLE_ID)
ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
    ADD CONSTRAINT FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BG FOREIGN KEY (BGM_AGIT_ROLE_ID)
        REFERENCES BGM_AGIT_ROLE (BGM_AGIT_ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_URL_RESOURCES_ROLE(BGM_AGIT_ROLE_ID)
-- ALTER TABLE BGM_AGIT_URL_RESOURCES_ROLE
-- DROP FOREIGN KEY FK_BGM_AGIT_URL_RESOURCES_ROLE_BGM_AGIT_ROLE_ID_BGM_AGIT_ROLE_BG;
