-- =====================================================================
-- 시계탑(Blood on the Clocktower) 플레이 기록 — 테이블 + 권한 + 메뉴 (MySQL 8.0)
-- ddl-auto: none 이므로 수동 실행.
--   CHARACTER_TYPE / PARTICIPANT_TYPE : TOWNSFOLK=마을주민, OUTSIDER=외부인, MINION=하수인, DEMON=악마
--   RECORD_RESULT  : GOOD_WIN=선인승, EVIL_WIN=악마승
-- =====================================================================

CREATE TABLE BGM_AGIT_CLOCKTOWER_GAME
(
    `BGM_AGIT_CLOCKTOWER_GAME_ID`          BIGINT          NOT NULL AUTO_INCREMENT COMMENT 'BGM 아지트 시계탑 게임 ID',
    `BGM_AGIT_CLOCKTOWER_GAME_NAME`        VARCHAR(500)    NULL     COMMENT '게임(시나리오) 이름',
    `BGM_AGIT_CLOCKTOWER_GAME_MIN_PEOPLE`  INT             NULL     COMMENT '최소 인원',
    `BGM_AGIT_CLOCKTOWER_GAME_MAX_PEOPLE`  INT             NULL     COMMENT '최대 인원',
    `BGM_AGIT_CLOCKTOWER_GAME_PLAY_TIME`   INT             NULL     COMMENT '예상 플레이타임(분)',
    `BGM_AGIT_CLOCKTOWER_GAME_IMAGE_URL`   VARCHAR(500)    NULL     COMMENT '커버 이미지 URL',
    `BGM_AGIT_CLOCKTOWER_USE_STATUS`       VARCHAR(1)      NULL     DEFAULT 'Y' COMMENT '사용 여부(Y/N)',
    `REGIST_DATE`                          DATETIME        NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                          DATETIME        NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_CLOCKTOWER_GAME_ID)
);
ALTER TABLE BGM_AGIT_CLOCKTOWER_GAME COMMENT 'BGM_아지트_시계탑_게임';

CREATE TABLE BGM_AGIT_CLOCKTOWER_CHARACTER
(
    `BGM_AGIT_CLOCKTOWER_CHARACTER_ID`          BIGINT        NOT NULL AUTO_INCREMENT COMMENT '캐릭터 ID',
    `BGM_AGIT_CLOCKTOWER_GAME_ID`               BIGINT        NULL     COMMENT '시계탑 게임 ID',
    `BGM_AGIT_CLOCKTOWER_CHARACTER_NAME`        VARCHAR(500)  NULL     COMMENT '캐릭터 이름',
    `BGM_AGIT_CLOCKTOWER_CHARACTER_TYPE`        VARCHAR(500)  NULL     COMMENT '역할군 TOWNSFOLK/OUTSIDER/MINION/DEMON',
    `BGM_AGIT_CLOCKTOWER_CHARACTER_DESCRIPTION` VARCHAR(4000) NULL     COMMENT '캐릭터 능력 설명',
    `BGM_AGIT_CLOCKTOWER_CHARACTER_ORDERS`      INT           NULL     COMMENT '표시 순서',
    `REGIST_DATE`                               DATETIME      NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                               DATETIME      NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_CLOCKTOWER_CHARACTER_ID)
);
ALTER TABLE BGM_AGIT_CLOCKTOWER_CHARACTER COMMENT 'BGM_아지트_시계탑_캐릭터';
CREATE INDEX IX_CLOCKTOWER_CHARACTER_GAME ON BGM_AGIT_CLOCKTOWER_CHARACTER (BGM_AGIT_CLOCKTOWER_GAME_ID);
ALTER TABLE BGM_AGIT_CLOCKTOWER_CHARACTER
    ADD CONSTRAINT FK_CLOCKTOWER_CHARACTER_GAME FOREIGN KEY (BGM_AGIT_CLOCKTOWER_GAME_ID)
        REFERENCES BGM_AGIT_CLOCKTOWER_GAME (BGM_AGIT_CLOCKTOWER_GAME_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE BGM_AGIT_CLOCKTOWER_RECORD
(
    `BGM_AGIT_CLOCKTOWER_RECORD_ID`     BIGINT        NOT NULL AUTO_INCREMENT COMMENT '시계탑 기록 ID',
    `BGM_AGIT_CLOCKTOWER_GAME_ID`       BIGINT        NULL     COMMENT '시계탑 게임 ID',
    `BGM_AGIT_MEMBER_ID`                BIGINT        NULL     COMMENT '작성자 회원 ID',
    `BGM_AGIT_CLOCKTOWER_RECORD_DATE`   DATE          NULL     COMMENT '플레이 날짜',
    `BGM_AGIT_CLOCKTOWER_RECORD_RESULT` VARCHAR(500)  NULL     COMMENT '결과 GOOD_WIN=선인승/EVIL_WIN=악마승',
    `BGM_AGIT_CLOCKTOWER_RECORD_MEMO`   VARCHAR(100)  NULL     COMMENT '메모',
    `REGIST_DATE`                       DATETIME      NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                       DATETIME      NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_CLOCKTOWER_RECORD_ID)
);
ALTER TABLE BGM_AGIT_CLOCKTOWER_RECORD COMMENT 'BGM_아지트_시계탑_기록';
CREATE INDEX IX_CLOCKTOWER_RECORD_DATE ON BGM_AGIT_CLOCKTOWER_RECORD (BGM_AGIT_CLOCKTOWER_RECORD_DATE);
ALTER TABLE BGM_AGIT_CLOCKTOWER_RECORD
    ADD CONSTRAINT FK_CLOCKTOWER_RECORD_GAME FOREIGN KEY (BGM_AGIT_CLOCKTOWER_GAME_ID)
        REFERENCES BGM_AGIT_CLOCKTOWER_GAME (BGM_AGIT_CLOCKTOWER_GAME_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BGM_AGIT_CLOCKTOWER_RECORD
    ADD CONSTRAINT FK_CLOCKTOWER_RECORD_MEMBER FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE BGM_AGIT_CLOCKTOWER_PARTICIPANT
(
    `BGM_AGIT_CLOCKTOWER_PARTICIPANT_ID`        BIGINT       NOT NULL AUTO_INCREMENT COMMENT '참가자 ID',
    `BGM_AGIT_CLOCKTOWER_RECORD_ID`             BIGINT       NULL     COMMENT '시계탑 기록 ID',
    `BGM_AGIT_MEMBER_ID`                        BIGINT       NULL     COMMENT '회원 ID',
    `BGM_AGIT_CLOCKTOWER_PARTICIPANT_CHARACTER` VARCHAR(500) NULL     COMMENT '플레이 캐릭터명(스냅샷)',
    `BGM_AGIT_CLOCKTOWER_PARTICIPANT_TYPE`      VARCHAR(500) NULL     COMMENT '역할군 스냅샷 TOWNSFOLK/OUTSIDER/MINION/DEMON',
    `REGIST_DATE`                               DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`                               DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_CLOCKTOWER_PARTICIPANT_ID),
    UNIQUE KEY UQ_CLOCKTOWER_PARTICIPANT (BGM_AGIT_CLOCKTOWER_RECORD_ID, BGM_AGIT_MEMBER_ID)
);
ALTER TABLE BGM_AGIT_CLOCKTOWER_PARTICIPANT COMMENT 'BGM_아지트_시계탑_참가자';
ALTER TABLE BGM_AGIT_CLOCKTOWER_PARTICIPANT
    ADD CONSTRAINT FK_CLOCKTOWER_PARTICIPANT_RECORD FOREIGN KEY (BGM_AGIT_CLOCKTOWER_RECORD_ID)
        REFERENCES BGM_AGIT_CLOCKTOWER_RECORD (BGM_AGIT_CLOCKTOWER_RECORD_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BGM_AGIT_CLOCKTOWER_PARTICIPANT
    ADD CONSTRAINT FK_CLOCKTOWER_PARTICIPANT_MEMBER FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- =====================================================================
-- 권한 매핑 (게임 카탈로그=ADMIN, 기록=USER. 소유권은 서비스가 추가 검증)
-- =====================================================================
INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD) VALUES ('/bgm-agit/clocktower-games', 'POST');
INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD) VALUES ('/bgm-agit/clocktower-games/*', 'PUT');
INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD) VALUES ('/bgm-agit/clocktower-games/*', 'DELETE');
INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD) VALUES ('/bgm-agit/clocktower-records', 'POST');
INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD) VALUES ('/bgm-agit/clocktower-records/*', 'PUT');
INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD) VALUES ('/bgm-agit/clocktower-records/*', 'DELETE');

INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
SELECT 1, BGM_AGIT_URL_RESOURCES_ID FROM BGM_AGIT_URL_RESOURCES
WHERE BGM_AGIT_URL_RESOURCES_PATH LIKE '/bgm-agit/clocktower-games%';

INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
SELECT 2, BGM_AGIT_URL_RESOURCES_ID FROM BGM_AGIT_URL_RESOURCES
WHERE BGM_AGIT_URL_RESOURCES_PATH LIKE '/bgm-agit/clocktower-records%';


-- =====================================================================
-- 메뉴 (부모 "시계탑" + 자식 3개)
-- =====================================================================
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK, BGM_AGIT_USE_STATUS, REGIST_DATE, MODIFY_DATE)
VALUES (NULL, 30, '시계탑', NULL, 1, NOW(), NOW());
SET @ct_parent = LAST_INSERT_ID();

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK, BGM_AGIT_USE_STATUS, REGIST_DATE, MODIFY_DATE)
VALUES (@ct_parent, 31, '시계탑 게임목록', '/clocktower-games', 1, NOW(), NOW());

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK, BGM_AGIT_USE_STATUS, REGIST_DATE, MODIFY_DATE)
VALUES (@ct_parent, 32, '시계탑 기록', '/clocktower-records', 1, NOW(), NOW());

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK, BGM_AGIT_USE_STATUS, REGIST_DATE, MODIFY_DATE)
VALUES (@ct_parent, 33, '시계탑 랭킹', '/clocktower-stats', 1, NOW(), NOW());

-- 메뉴 권한: 시계탑 부모+자식 전부 USER(2)+ADMIN(1)
INSERT INTO BGM_AGIT_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_MAIN_MENU_ID, REGIST_DATE, MODIFY_DATE)
SELECT r.rid, m.BGM_AGIT_MAIN_MENU_ID, NOW(), NOW()
FROM (SELECT 1 rid UNION SELECT 2) r
CROSS JOIN BGM_AGIT_MAIN_MENU m
WHERE m.BGM_AGIT_MENU_LINK IN ('/clocktower-games', '/clocktower-records', '/clocktower-stats')
   OR m.BGM_AGIT_MAIN_MENU_ID = @ct_parent;
