-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- BGM_AGIT_MAIN_MENU Table Create SQL
-- 테이블 생성 SQL - BGM_AGIT_MAIN_MENU
CREATE TABLE BGM_AGIT_MAIN_MENU
(
    `BGM_AGIT_MAIN_MENU_ID`  BIGINT           NOT NULL    AUTO_INCREMENT COMMENT 'BGM 아지트 메인 메뉴 ID',
    `BGM_AGIT_SUB_MENU_ID`   BIGINT           NULL        COMMENT 'BGM 아지트 서브 메뉴 ID',
    `BGM_AGIT_AREA_ID`       BIGINT           NULL        COMMENT 'BGM 아지트 영역 ID',
    `BGM_AGIT_MENU_NAME`     VARCHAR(4000)    NULL        COMMENT 'BGM 아지트 메뉴 이름',
    `REGIST_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `MODIFY_DATE`            DATETIME         NULL        DEFAULT CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (BGM_AGIT_MAIN_MENU_ID)
);

-- 테이블 Comment 설정 SQL - BGM_AGIT_MAIN_MENU
ALTER TABLE BGM_AGIT_MAIN_MENU COMMENT 'BGM_아지트_메인_메뉴';

-- Foreign Key 설정 SQL - BGM_AGIT_MAIN_MENU(BGM_AGIT_SUB_MENU_ID) -> BGM_AGIT_MAIN_MENU(BGM_AGIT_MAIN_MENU_ID)
ALTER TABLE BGM_AGIT_MAIN_MENU
    ADD CONSTRAINT FK_BGM_AGIT_MAIN_MENU_BGM_AGIT_SUB_MENU_ID_BGM_AGIT_MAIN_MENU_BG FOREIGN KEY (BGM_AGIT_SUB_MENU_ID)
        REFERENCES BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - BGM_AGIT_MAIN_MENU(BGM_AGIT_SUB_MENU_ID)
-- ALTER TABLE BGM_AGIT_MAIN_MENU
-- DROP FOREIGN KEY FK_BGM_AGIT_MAIN_MENU_BGM_AGIT_SUB_MENU_ID_BGM_AGIT_MAIN_MENU_BG;


