INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU
    (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON)
VALUES
    (16, 'URL 권한', '/url-role', 3, 'Gear');

SET @URL_ROLE_MENU_ID = LAST_INSERT_ID();

INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE
    (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID)
SELECT BGM_AGIT_ROLE_ID, @URL_ROLE_MENU_ID
FROM BGMAGIT.BGM_AGIT_ROLE
WHERE BGM_AGIT_ROLE_NAME = 'ADMIN';

INSERT INTO BGMAGIT.BGM_AGIT_URL_RESOURCES
    (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD)
VALUES
    ('/bgm-agit/url-roles', 'GET'),
    ('/bgm-agit/url-roles', 'POST'),
    ('/bgm-agit/url-roles/roles', 'GET');

INSERT INTO BGMAGIT.BGM_AGIT_URL_RESOURCES_ROLE
    (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
SELECT role.BGM_AGIT_ROLE_ID, resources.BGM_AGIT_URL_RESOURCES_ID
FROM BGMAGIT.BGM_AGIT_ROLE role
CROSS JOIN BGMAGIT.BGM_AGIT_URL_RESOURCES resources
WHERE role.BGM_AGIT_ROLE_NAME = 'ADMIN'
  AND (
      (resources.BGM_AGIT_URL_RESOURCES_PATH = '/bgm-agit/url-roles' AND resources.BGM_AGIT_URL_HTTP_METHOD IN ('GET', 'POST'))
      OR (resources.BGM_AGIT_URL_RESOURCES_PATH = '/bgm-agit/url-roles/roles' AND resources.BGM_AGIT_URL_HTTP_METHOD = 'GET')
  );
