
INSERT INTO BGMAGIT.BGM_AGIT_SETTING (BGM_AGIT_SETTING_TURNING, BGM_AGIT_SETTING_FIRST_UMA, BGM_AGIT_SETTING_SECOND_UMA, BGM_AGIT_SETTING_THIRD_UMA, BGM_AGIT_SETTING_FOUR_UMA, BGM_AGIT_SETTING_USE_STATUS) VALUES (30000, 10, 5, -5, -10, 'Y');

INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '공지사항', '/notice', 1, 'Bell');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '마작/대회 룰', '/rule', 2, 'BookOpen');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '월간/일간기록', '/day-record', 3, 'CalendarBlank');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '역만기록', '/yakuman-record', 4, 'Crown');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '연간기록', '/years-record', 5, 'ChartLineUp');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '대회 기록', '/tournament-record', 6, 'PencilSimple');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '반환점/우마 설정', '/setting', 8, 'Gear');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '마작 아카데미', '/sub', 9, 'GraduationCap');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (8, '마작이란?', '/guide', 1, 'Compass');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (8, '예약 및 매칭', '/matches', 2, 'Handshake');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (8, '마작 아카데미 후기', '/review', 3, 'ChatsCircle');
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU (BGM_AGIT_KML_SUB_MENU_ID, BGM_AGIT_KML_MENU_NAME, BGM_AGIT_KML_MENU_LINK, BGM_AGIT_KML_MENU_ORDERS, BGM_AGIT_KML_ICON) VALUES (null, '아카데미 예약내역', '/my-academy', 10, null);


INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 1);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 2);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 3);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 4);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 5);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 6);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (1, 7);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 8);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 9);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 10);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (3, 11);
INSERT INTO BGMAGIT.BGM_AGIT_KML_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_KML_MENU_ID) VALUES (2, 12);
