
SET FOREIGN_KEY_CHECKS  =0;
TRUNCATE BGM_AGIT_MAIN_MENU;
TRUNCATE BGM_AGIT_MENU_ROLE;
SET FOREIGN_KEY_CHECKS  =1;



INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (null, 1, '소개', null);
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (null, 2, '예약하기', null);
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (null, 3, '마작 아카데미', null);
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (null, 4, '메뉴', null);
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (null, 5, '커뮤니티', null);
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (null, 6, '마이페이지', null);

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,1);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,2);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,3);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,4);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,5);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (2,6);


INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (1, 1, '보유게임', '/detail/game');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (1, 2, 'BGM아지트 소개', '/about');

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,7);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,8);

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (2, 1, '룸', '/detail/room');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (2, 2, '대탁', '/detail/mahjongRental');

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,9);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,10);

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (3, 1, '마작이란?', '/guide');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (3, 2, '마작 교육 예약', '/matches');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (3, 3, '마작 아카데미 후기', '/review');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (3, 4, '교육 문의', 'https://open.kakao.com/o/snQNUPre');

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,11);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,12);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,13);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,14);

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (4, 1, '음료', '/detail/drink');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (4, 2, '식사', '/detail/food');

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,15);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,16);

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (5, 1, '공지사항', '/notice');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (5, 2, '자유 게시판', '/free');

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,17);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (3,18);


INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (6, 1, '예약내역', '/reservationList');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (6, 2, '권한 관리', '/role');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (6, 3, '내정보', '/mypage');
INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (6, 4, '1:1문의', '/inquiry');

INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (2,19);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (1,20);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (2,21);
INSERT INTO BGM_AGIT_MENU_ROLE(BGM_AGIT_ROLE_ID,BGM_AGIT_MAIN_MENU_ID) VALUES (2,22);


