INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME)
VALUES (NULL, NULL, '소개');

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME)
VALUES (NULL, NULL, '예약하기');

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME)
VALUES (NULL, NULL, '메뉴');

INSERT INTO BGM_AGIT_MAIN_MENU (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME)
VALUES (NULL, NULL, '커뮤니티');


INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (1, null, null, '소개', null);
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (2, null, null, '예약하기', null);
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (3, null, null, '메뉴', null);
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (4, null, null, '커뮤니티', null);
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (5, 1, null, 'BGM아지트 소개', '/about');
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (6, 1, null, '보유게임', '/detail/game');
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (7, 2, null, '룸', '/detail/room');
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (8, 2, null, '대탁', null);
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (9, 2, null, '마작강의 예약', null);
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (10, 3, null, '음료', '/detail/drink');
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (11, 3, null, '식사', '/detail/food');
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (12, 4, null, '공지사항', '/notice');
INSERT INTO BGMAGIT.BGM_AGIT_MAIN_MENU (BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK) VALUES (13, 4, null, '게시판', null);




INSERT INTO BGMAGIT.BGM_AGIT_ROLE ( BGM_AGIT_ROLE_NAME) VALUES ( 'ADMIN');
INSERT INTO BGMAGIT.BGM_AGIT_ROLE ( BGM_AGIT_ROLE_NAME) VALUES ( 'USER');
INSERT INTO BGMAGIT.BGM_AGIT_ROLE ( BGM_AGIT_ROLE_NAME) VALUES ( 'ANONYMOUS');


INSERT INTO BGM_AGIT_ROLE_HIERARCHY( BGM_AGIT_ROLE_NAME, BGM_AGIT_PARENT_ROLE_ID)
VALUES ('ADMIN', NULL);

INSERT INTO BGM_AGIT_ROLE_HIERARCHY( BGM_AGIT_ROLE_NAME, BGM_AGIT_PARENT_ROLE_ID)
VALUES ('USER', 1);

INSERT INTO BGM_AGIT_ROLE_HIERARCHY( BGM_AGIT_ROLE_NAME, BGM_AGIT_PARENT_ROLE_ID)
VALUES ('ANONYMOUS', 2);


INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH) VALUES
    ('/bgm-agit/main-menu');

INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH) VALUES
    ('/bgm-agit/reservation');

INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH) VALUES
    ('/bgm-agit/food');

INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH) VALUES
    ('/bgm-agit/game');

INSERT INTO BGM_AGIT_URL_RESOURCES ( BGM_AGIT_URL_RESOURCES_PATH) VALUES
    ('/bgm-agit/kakao-login');

INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
VALUES(3, 1); -- /bgm-agit/main-menu
INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
VALUES (3, 2); -- /bgm-agit/reservation
INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
VALUES(3, 3); -- /bgm-agit/food
INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
VALUES(3, 4); -- /bgm-agit/game
INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID)
VALUES(3, 5); -- /bgm-agit/kakao-login


commit;