-- 서비스 요청(유지보수 요청) 게시판 — 관리자 전용
--
-- ddl-auto: none 이라 수동 실행. 앱 배포 **전에** 돌린다(테이블이 없으면 화면이 500).
-- mysql 클라이언트로 실행할 때 --default-character-set=utf8mb4 를 붙일 것.
-- 전부 재실행해도 안전하다(IF NOT EXISTS / NOT EXISTS).

-- 1) 테이블 — BGM_AGIT_INQUIRY 와 같은 모양. 본문은 CKEditor HTML(이미지 태그 포함)이라 TEXT 로 넉넉히 둔다
CREATE TABLE IF NOT EXISTS BGM_AGIT_SERVICE_REQUEST (
    BGM_AGIT_SERVICE_REQUEST_ID            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '서비스 요청 ID',
    BGM_AGIT_SERVICE_REQUEST_HIERARCHY_ID  BIGINT       NULL COMMENT '답변이면 원글 ID',
    BGM_AGIT_MEMBER_ID                     BIGINT       NOT NULL COMMENT '작성자',
    BGM_AGIT_SERVICE_REQUEST_TITLE         VARCHAR(500) NOT NULL COMMENT '제목',
    BGM_AGIT_SERVICE_REQUEST_CONT          MEDIUMTEXT   NOT NULL COMMENT '내용',
    BGM_AGIT_SERVICE_REQUEST_ANSWER_STATUS VARCHAR(1)   NOT NULL DEFAULT 'N' COMMENT '처리 여부 Y/N',
    REGIST_DATE                            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE                            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BGM_AGIT_SERVICE_REQUEST_ID),
    KEY IDX_SERVICE_REQUEST_HIERARCHY (BGM_AGIT_SERVICE_REQUEST_HIERARCHY_ID),
    CONSTRAINT FK_SERVICE_REQUEST_MEMBER FOREIGN KEY (BGM_AGIT_MEMBER_ID)
        REFERENCES BGM_AGIT_MEMBER (BGM_AGIT_MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_SERVICE_REQUEST_HIERARCHY FOREIGN KEY (BGM_AGIT_SERVICE_REQUEST_HIERARCHY_ID)
        REFERENCES BGM_AGIT_SERVICE_REQUEST (BGM_AGIT_SERVICE_REQUEST_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'BGM_아지트_서비스요청';

-- 2) 권한 매핑 — 컨트롤러에도 관리자 검사가 있지만 둘 다 둔다.
--    **INSERT 후 앱 재시작 필요** (매핑 로딩이 @PostConstruct 1회). 앱 배포 전에 넣으면 배포 재시작으로 해결된다
START TRANSACTION;

INSERT INTO BGM_AGIT_URL_RESOURCES (BGM_AGIT_URL_RESOURCES_PATH, BGM_AGIT_URL_HTTP_METHOD, REGIST_DATE)
SELECT v.path, v.method, NOW()
  FROM (SELECT '/bgm-agit/service-request' AS path, 'GET' AS method
        UNION ALL SELECT '/bgm-agit/service-request',    'POST'
        UNION ALL SELECT '/bgm-agit/service-request',    'PUT'
        UNION ALL SELECT '/bgm-agit/service-request/**', 'GET'
        UNION ALL SELECT '/bgm-agit/service-request/**', 'POST'
        UNION ALL SELECT '/bgm-agit/service-request/**', 'DELETE') v
 WHERE NOT EXISTS (
       SELECT 1 FROM BGM_AGIT_URL_RESOURCES u
        WHERE u.BGM_AGIT_URL_RESOURCES_PATH = v.path
          AND u.BGM_AGIT_URL_HTTP_METHOD = v.method);

-- 관리자(1)만
INSERT INTO BGM_AGIT_URL_RESOURCES_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_URL_RESOURCES_ID, REGIST_DATE)
SELECT 1, u.BGM_AGIT_URL_RESOURCES_ID, NOW()
  FROM BGM_AGIT_URL_RESOURCES u
 WHERE u.BGM_AGIT_URL_RESOURCES_PATH IN ('/bgm-agit/service-request', '/bgm-agit/service-request/**')
   AND NOT EXISTS (
       SELECT 1 FROM BGM_AGIT_URL_RESOURCES_ROLE r
        WHERE r.BGM_AGIT_URL_RESOURCES_ID = u.BGM_AGIT_URL_RESOURCES_ID
          AND r.BGM_AGIT_ROLE_ID = 1);

COMMIT;

-- 3) 메뉴 — getMainMenu 가 subMenu 없는 root 를 걸러내므로 기존 부모 하위로.
--    관리자 화면인 "예약 현황판"(/reservation-board) 과 같은 부모 밑 맨 뒤에 넣고, 메뉴 권한은 관리자(1)만
START TRANSACTION;

INSERT INTO BGM_AGIT_MAIN_MENU
       (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK, BGM_AGIT_USE_STATUS, REGIST_DATE)
SELECT x.parent_id, x.next_area, '서비스 요청', '/service-request', 1, NOW()
  FROM (SELECT b.BGM_AGIT_SUB_MENU_ID AS parent_id,
               (SELECT COALESCE(MAX(s.BGM_AGIT_AREA_ID), 0) + 1
                  FROM BGM_AGIT_MAIN_MENU s
                 WHERE s.BGM_AGIT_SUB_MENU_ID = b.BGM_AGIT_SUB_MENU_ID) AS next_area
          FROM BGM_AGIT_MAIN_MENU b
         WHERE b.BGM_AGIT_MENU_LINK = '/reservation-board'
         LIMIT 1) x
 WHERE NOT EXISTS (
       SELECT 1 FROM (SELECT BGM_AGIT_MENU_LINK FROM BGM_AGIT_MAIN_MENU) m
        WHERE m.BGM_AGIT_MENU_LINK = '/service-request');

INSERT INTO BGM_AGIT_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_MAIN_MENU_ID)
SELECT 1, m.BGM_AGIT_MAIN_MENU_ID
  FROM BGM_AGIT_MAIN_MENU m
 WHERE m.BGM_AGIT_MENU_LINK = '/service-request'
   AND NOT EXISTS (
       SELECT 1 FROM BGM_AGIT_MENU_ROLE r
        WHERE r.BGM_AGIT_MAIN_MENU_ID = m.BGM_AGIT_MAIN_MENU_ID
          AND r.BGM_AGIT_ROLE_ID = 1);

COMMIT;

-- 결과 확인
SELECT u.BGM_AGIT_URL_RESOURCES_ID AS url_id, u.BGM_AGIT_URL_RESOURCES_PATH AS path,
       u.BGM_AGIT_URL_HTTP_METHOD AS method,
       GROUP_CONCAT(r.BGM_AGIT_ROLE_ID ORDER BY r.BGM_AGIT_ROLE_ID) AS role_ids
  FROM BGM_AGIT_URL_RESOURCES u
  LEFT JOIN BGM_AGIT_URL_RESOURCES_ROLE r ON r.BGM_AGIT_URL_RESOURCES_ID = u.BGM_AGIT_URL_RESOURCES_ID
 WHERE u.BGM_AGIT_URL_RESOURCES_PATH LIKE '/bgm-agit/service-request%'
 GROUP BY 1, 2, 3;

SELECT m.BGM_AGIT_MAIN_MENU_ID AS id, m.BGM_AGIT_SUB_MENU_ID AS parent_id, m.BGM_AGIT_MENU_NAME AS name,
       m.BGM_AGIT_MENU_LINK AS link, m.BGM_AGIT_AREA_ID AS area,
       GROUP_CONCAT(r.BGM_AGIT_ROLE_ID) AS role_ids
  FROM BGM_AGIT_MAIN_MENU m
  LEFT JOIN BGM_AGIT_MENU_ROLE r ON r.BGM_AGIT_MAIN_MENU_ID = m.BGM_AGIT_MAIN_MENU_ID
 WHERE m.BGM_AGIT_MENU_LINK = '/service-request'
 GROUP BY 1, 2, 3, 4, 5;

-- 롤백
-- DELETE FROM BGM_AGIT_MENU_ROLE WHERE BGM_AGIT_MAIN_MENU_ID IN (
--   SELECT id FROM (SELECT BGM_AGIT_MAIN_MENU_ID id FROM BGM_AGIT_MAIN_MENU WHERE BGM_AGIT_MENU_LINK = '/service-request') t);
-- DELETE FROM BGM_AGIT_MAIN_MENU WHERE BGM_AGIT_MENU_LINK = '/service-request';
-- DELETE FROM BGM_AGIT_URL_RESOURCES_ROLE WHERE BGM_AGIT_URL_RESOURCES_ID IN (
--   SELECT id FROM (SELECT BGM_AGIT_URL_RESOURCES_ID id FROM BGM_AGIT_URL_RESOURCES
--                    WHERE BGM_AGIT_URL_RESOURCES_PATH LIKE '/bgm-agit/service-request%') t);
-- DELETE FROM BGM_AGIT_URL_RESOURCES WHERE BGM_AGIT_URL_RESOURCES_PATH LIKE '/bgm-agit/service-request%';
-- DROP TABLE IF EXISTS BGM_AGIT_SERVICE_REQUEST;
