-- 서비스 요청 메뉴를 마이페이지 하위에서 최상위 메뉴로 분리 (마이페이지 하위가 너무 길어서)
--
-- getMainMenu 가 subMenu 없는 root 를 걸러내므로 root "서비스 요청" + 하위 "서비스 요청"(/service-request) 구조로 둔다.
-- root 는 마이페이지(area 6) 바로 뒤 area 7. 권한은 둘 다 관리자(1)만.
-- service-request.sql 을 먼저 실행한 뒤 돌린다. 재실행해도 안전하다.

START TRANSACTION;

-- 1) 최상위 메뉴
INSERT INTO BGM_AGIT_MAIN_MENU
       (BGM_AGIT_SUB_MENU_ID, BGM_AGIT_AREA_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_MENU_LINK, BGM_AGIT_USE_STATUS, REGIST_DATE)
SELECT NULL, 7, '서비스 요청', NULL, 1, NOW()
  FROM DUAL
 WHERE NOT EXISTS (
       SELECT 1 FROM (SELECT BGM_AGIT_MAIN_MENU_ID, BGM_AGIT_MENU_NAME, BGM_AGIT_SUB_MENU_ID FROM BGM_AGIT_MAIN_MENU) m
        WHERE m.BGM_AGIT_SUB_MENU_ID IS NULL AND m.BGM_AGIT_MENU_NAME = '서비스 요청');

INSERT INTO BGM_AGIT_MENU_ROLE (BGM_AGIT_ROLE_ID, BGM_AGIT_MAIN_MENU_ID)
SELECT 1, m.BGM_AGIT_MAIN_MENU_ID
  FROM BGM_AGIT_MAIN_MENU m
 WHERE m.BGM_AGIT_SUB_MENU_ID IS NULL AND m.BGM_AGIT_MENU_NAME = '서비스 요청'
   AND NOT EXISTS (
       SELECT 1 FROM BGM_AGIT_MENU_ROLE r
        WHERE r.BGM_AGIT_MAIN_MENU_ID = m.BGM_AGIT_MAIN_MENU_ID AND r.BGM_AGIT_ROLE_ID = 1);

-- 2) 기존 /service-request 메뉴를 새 root 하위 1번으로 이동
UPDATE BGM_AGIT_MAIN_MENU c
  JOIN (SELECT BGM_AGIT_MAIN_MENU_ID AS id FROM BGM_AGIT_MAIN_MENU
         WHERE BGM_AGIT_SUB_MENU_ID IS NULL AND BGM_AGIT_MENU_NAME = '서비스 요청' LIMIT 1) root
   SET c.BGM_AGIT_SUB_MENU_ID = root.id,
       c.BGM_AGIT_AREA_ID = 1,
       c.MODIFY_DATE = NOW()
 WHERE c.BGM_AGIT_MENU_LINK = '/service-request';

COMMIT;

-- 결과 확인
SELECT m.BGM_AGIT_MAIN_MENU_ID AS id, m.BGM_AGIT_SUB_MENU_ID AS parent_id, m.BGM_AGIT_AREA_ID AS area,
       m.BGM_AGIT_MENU_NAME AS name, m.BGM_AGIT_MENU_LINK AS link, m.BGM_AGIT_USE_STATUS AS use_yn,
       GROUP_CONCAT(r.BGM_AGIT_ROLE_ID) AS role_ids
  FROM BGM_AGIT_MAIN_MENU m
  LEFT JOIN BGM_AGIT_MENU_ROLE r ON r.BGM_AGIT_MAIN_MENU_ID = m.BGM_AGIT_MAIN_MENU_ID
 WHERE m.BGM_AGIT_MENU_NAME = '서비스 요청'
 GROUP BY 1, 2, 3, 4, 5, 6;

-- 롤백 (마이페이지 하위로 되돌림)
-- UPDATE BGM_AGIT_MAIN_MENU c
--   JOIN (SELECT BGM_AGIT_SUB_MENU_ID AS pid, COALESCE(MAX(BGM_AGIT_AREA_ID),0)+1 AS area FROM BGM_AGIT_MAIN_MENU
--          WHERE BGM_AGIT_MENU_LINK = '/reservation-board' GROUP BY BGM_AGIT_SUB_MENU_ID) x
--    SET c.BGM_AGIT_SUB_MENU_ID = x.pid WHERE c.BGM_AGIT_MENU_LINK = '/service-request';
-- DELETE FROM BGM_AGIT_MENU_ROLE WHERE BGM_AGIT_MAIN_MENU_ID IN (SELECT id FROM (SELECT BGM_AGIT_MAIN_MENU_ID id FROM BGM_AGIT_MAIN_MENU
--   WHERE BGM_AGIT_SUB_MENU_ID IS NULL AND BGM_AGIT_MENU_NAME = '서비스 요청') t);
-- DELETE FROM BGM_AGIT_MAIN_MENU WHERE BGM_AGIT_SUB_MENU_ID IS NULL AND BGM_AGIT_MENU_NAME = '서비스 요청';
