spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:  jdbc:log4jdbc:mysql://${DB_URL}:${DB_PORT}/BGMAGIT
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET}

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256

logging:
  file:
    name: /app/logs/bgmagit.log
    level:
      root: INFO
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log


cors:
  url: https://bgmagit.co.kr

kakao:
  redirecturi: https://bgmagit.co.kr/oauth/kakao/callback
  clientId: 1c5346963ea4efa00362b4f1f2533a4c

jwt:
  secret: ${JWT_SECRET}