spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_URL}:${DB_PORT}/BGMAGIT
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET}

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256
          jwk-set-uri: http://localhost:8080/bgm-agit/.well-known/jwks.json

  jackson:
        time-zone: Asia/Seoul
cors:
  url: http://localhost:5173

kakao:
  redirecturi: http://localhost:5173/oauth/kakao/callback
  clientId: 1c41b5cad9dceea3074ad92a6d496215
  client-secret: ${CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}

cookie:
  secure: false

biztalk:
  id: ${BIZTALK_ID}
  password: ${BIZTALK_PASSWORD}